

* todo

** TODO rename input 'colors' or output 'colors'
** TODO add switch for outputing raw run data
** TODO add calculation of variance over a run

   Boost accumulators can calculate mean and variance incrementally.
   faster to do calculate on complete results of run?

** DONE setup macro for debug logging

*** ezlogger?
    http://axter.com/ezlogger/

  * boost logging?

  * went with TRACE macro

** DONE implement func for doing runs 

** DONE better randomness

   switch to <tr1/random>
   verify re-seeding works as expected thru python library.
   http://www.boost.org/doc/libs/1_39_0/libs/random/index.html

   tried. but performance slower.
** TODO lookinto perf possibilities

   need to configure alphabetsize and string size at runtime.

*** TODO intertwingle search() and calculate_measures()

    with rolling all operations into one loop

    instead of re-iterating thru the map to calc stats, should just
    calc stats as the search goes

    so instead of building one map observed, build two: cluster and
    perimeter. and keep a running count of their size.

*** replace set_difference and set_intersection

    with nonconsing versions.

*** alternative representations for geno

   Issues: std::string dynamically allocates storage.
   - calls to malloc slower than stack allocation
   - indirection required for every lookup

   Issues: std::string optimized for alphabetsize =256 (extended ASCII).
   - fatter representation, more copying, worse caching

    uint (interpret string as number where base=alphabetsize)?
    short[]
    char[]
    basic_string<customCharT>
      where CustomType in {enum with alphabetsize elements}

*** std::string::reserve() to hint runtime to free excess memory

*** optimizations of mut()

   instead of generating alternative alphabet letters, do lookup from
   static table?

   instead of building adding mutants incrementally, create whole
   block of original string with 
   vector<string>( (alphabetsize-1)*(length), geno)
   and then mutate thee chars individually?
   (requires ability to mutate vector's elems, rather than copy them.)
   
  Issues: generation of mutants also needs to be fast.
   - possibly SLOWER with representation as a unit
     - 
 


*** recompile with libc++

    http://developer.apple.com/library/mac/#documentation/CompilerTools/Conceptual/index.html


    performance ranking:
    clang++, compiling libstdcxx-gcc4.2, with boost::tr1::unordered_map
    clang++, compiling libstdcxx-gcc4.2, with stdcxx-gcc4.2 unordered_map
    clang++ compiling libc++
    clang++ compiling libc++ with std=c++0x gives errors

    clang++ beats g++4.2

*** boost::tr1::unordered_map outperforming gcc-4.2/unordered_map

*** tuned hashing function for unordered_map

*** better unordered_map or unordered_set

    use djb's cribit?
    http://www.imperialviolet.org/binary/critbit.pdf

*** replace std::string with something customized?
compile with std=c++0x to ensure return value optimization

* neutral model


** these are Hamming Graphs

** Point1: E and r correlated
*** Wagner's E vs. r argument
*** preimage stats vs. cluster stats
** what conditions produce maximum correlation?
** what are the main dynamics effecting E and
** inputs vs outputs:  
  
*** cluster growth phase

    (a, l, m, RAND) -> S
    S + \del -> T
    S -> s
    S + T -> U
    T -> t
    U -> u
    (s,u,l,a) -> r

*** cereal box phase

    T + \phi -> E

** <E> vs m. the hump

** correlation

** parameter regimes and their chief dynamics
*** m drives <t> which bounds <E>
**** low m ( m << t)
    too few colors to fill all the slots
**** high m ( m >> t )
    too few slots to accommodate all the colors

*** growth process

    bimodal distribution in <s>. Hardest hurdle is first generation of
    search. many graphs die as singletons.

*** effect of l (string length, als

*** effect of a (alphabet size)

** uniform vs skewed distribution
*** skewed distribution
    
    adds new factor: randomization of initial starting color

    increasing skew has an effect on the cereal box part of the
    problem: decreases number of expected colors seen

    increasing skew has an effect on the graph growth part of the
    problem: 
       
** diagrams
*** set S, perimeter T, exits U
*** <E> vs m
*** 


    
* motivation
* model
** Hamming graph represents mutation graph
** randomly assign colors (i.e., phenotypes) to nodes
* conclusions

